import { useEffect, useMemo, useState } from 'react'
import { demoResources, getResources, saveResource } from './lib/api'

export default function Dashboard({ onOpenLibrary, onSave }) {
  const [resources, setResources] = useState(demoResources)
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All resources')
  useEffect(() => { getResources().then(setResources) }, [])
  const filteredResources = useMemo(() => resources.filter((resource) => `${resource.title} ${resource.organization} ${resource.tag}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All resources' || resource.type === filter)), [filter, query, resources])
  return <div className="content-wrap">
    <section className="welcome"><div><p className="eyebrow">WEDNESDAY, 30 SEPTEMBER 2026</p><h1>Good morning, Ananya <span>✦</span></h1><p className="lede">Your national land governance intelligence brief is ready.</p></div><button className="outline-button">＋ <span>New workspace</span></button></section>
    <section className="signal-row"><div className="signal-card primary"><div className="signal-top"><span className="signal-icon">◒</span><span className="trend up">↗ 12.4%</span></div><strong>1,284</strong><span>Research resources added</span><div className="sparkline">{Array.from({ length: 12 }, (_, index) => <i key={index}></i>)}</div></div><div className="signal-card"><div className="signal-top"><span className="signal-icon amber">⌁</span><span className="trend up">↗ 8.1%</span></div><strong>38</strong><span>Active policy experiments</span><div className="mini-bars">{Array.from({ length: 8 }, (_, index) => <i key={index}></i>)}</div></div><div className="signal-card"><div className="signal-top"><span className="signal-icon coral">◉</span><span className="trend neutral">On track</span></div><strong>72<span className="unit">%</span></strong><span>National data coverage</span><div className="progress"><i></i></div></div><div className="signal-card question-card"><span className="question-mark">?</span><div><strong>Shape the next brief</strong><span>Tell us what you are researching</span></div><button>→</button></div></section>
    <section className="dashboard-grid"><div className="panel map-panel"><div className="panel-heading"><div><p className="eyebrow">LAND INTELLIGENCE</p><h2>India at a glance</h2></div><button className="dots">•••</button></div><div className="map-stage"><div className="map-grid"></div><div className="india-shape"><span className="map-pin pin-one"></span><span className="map-pin pin-two"></span><span className="map-pin pin-three"></span><span className="map-pin pin-four"></span><span className="map-pin pin-five"></span></div><div className="map-label label-north">NORTH EAST<br/><b>CLIMATE RISK</b></div><div className="map-label label-west">WESTERN<br/><b>URBAN GROWTH</b></div><div className="map-label label-south">SOUTHERN<br/><b>LAND COVER</b></div><div className="map-controls"><button>＋</button><button>−</button><button>⌖</button></div><div className="map-legend"><span><i className="legend-mint"></i>Low risk</span><span><i className="legend-yellow"></i>Moderate</span><span><i className="legend-coral"></i>High risk</span></div></div><div className="map-footer"><div><strong>7.4M</strong><span>hectares monitored</span></div><div><strong>18</strong><span>live layers</span></div><button>Explore intelligence →</button></div></div><div className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">YOUR SIGNAL</p><h2>Recent activity</h2></div><button className="text-button">View all →</button></div><div className="activity-list"><div className="activity-item"><div className="activity-icon coral-bg">↗</div><div><strong>Policy brief published</strong><span>Urban land value capture · MoHUA</span><small>2 hours ago</small></div></div><div className="activity-item"><div className="activity-icon mint-bg">♧</div><div><strong>New dataset available</strong><span>District-level land disputes · 2024</span><small>Yesterday</small></div></div><div className="activity-item"><div className="activity-icon blue-bg">⌁</div><div><strong>Workspace update</strong><span>3 collaborators joined “Coastal Resilience”</span><small>2 days ago</small></div></div></div><div className="activity-note"><span>✦</span><div><strong>AI insight</strong><p>Land use research in coastal districts has grown <b>23%</b> this quarter.</p></div></div></div></section>
    <section className="library-section"><div className="section-heading"><div><p className="eyebrow">DISCOVER KNOWLEDGE</p><h2>Research library</h2></div><button className="text-button" onClick={onOpenLibrary}>Open library →</button></div><div className="library-tools"><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search research, data, policy..." /><kbd>⌘ K</kbd></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All resources</option><option>Research paper</option><option>Policy brief</option><option>Case study</option><option>Implementation guide</option></select><button className="filter-button">☷ Filters</button></div><div className="resource-grid">{filteredResources.map((resource) => <article className="resource-card" key={resource.id}><div className={`resource-art ${resource.tone || 'mint'}`}><span>{resource.tag}</span><button onClick={() => { onSave(resource.id); saveResource(resource.id) }} aria-label={`Save ${resource.title}`}>☆</button><div className="art-lines"></div></div><div className="resource-body"><div className="resource-meta"><span>{resource.type}</span><span>•</span><span>{resource.organization} · {resource.year}</span></div><h3>{resource.title}</h3><button className="read-link">Read resource <span>→</span></button></div></article>)}</div></section>
    <section className="innovation-strip"><div><p className="eyebrow">FROM THE INNOVATION HUB</p><h2>Turn evidence into action.</h2><p>Find open calls, pilot partners, and challenges shaping the next generation of land governance.</p></div><div className="innovation-stats"><div><strong>12</strong><span>Open calls</span></div><div><strong>28</strong><span>Active pilots</span></div><button>Explore hub →</button></div></section>
  </div>
}
