import { useEffect, useMemo, useState } from 'react'
import { createWorkspace, demoCalls, demoExperiments, demoResources, getExperiments, getInnovationCalls, getResources, saveResource } from './lib/api'

const pageMeta = {
  'Research library': ['DISCOVER KNOWLEDGE', 'Research library', 'Search India\'s growing evidence base on land governance.'],
  'Land intelligence': ['NATIONAL GEO-SPATIAL VIEW', 'Land intelligence', 'Explore signals across land use, climate vulnerability, and infrastructure.'],
  'Policy lab': ['EXPERIMENT BEFORE IMPLEMENTATION', 'Policy lab', 'Track live policy experiments and compare their progress.'],
  Collaborate: ['SHARED WORKSPACES', 'Collaborate', 'Bring researchers, officials, and institutions around a shared question.'],
  'Innovation hub': ['OPEN INNOVATION', 'Innovation hub', 'Find pilots, grants, hackathons, and research opportunities.'],
}

export function PageFrame({ page, children }) {
  const [eyebrow, title, description] = pageMeta[page]
  return <section className="page-view"><div className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><span className="page-count">{page === 'Research library' ? '1,284 resources' : page === 'Policy lab' ? '38 experiments' : 'National network'}</span></div>{children}</section>
}

export function ResearchLibrary({ onSave }) {
  const [resources, setResources] = useState(demoResources)
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All resources')
  useEffect(() => { getResources().then(setResources) }, [])
  const filtered = useMemo(() => resources.filter((item) => `${item.title} ${item.organization} ${item.tag} ${item.description}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All resources' || item.type === filter)), [filter, query, resources])
  return <PageFrame page="Research library"><div className="library-tools page-tools"><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search research, policy, data..." /><kbd>⌘ K</kbd></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All resources</option><option>Research paper</option><option>Policy brief</option><option>Case study</option><option>Implementation guide</option><option>Dataset</option></select><button className="filter-button">☷ Filters</button></div><div className="resource-grid library-grid">{filtered.map((resource) => <article className="resource-card" key={resource.id}><div className={`resource-art ${resource.tone || 'mint'}`}><span>{resource.tag}</span><button onClick={() => { onSave(resource.id); saveResource(resource.id) }} aria-label={`Save ${resource.title}`}>☆</button><div className="art-lines"></div></div><div className="resource-body"><div className="resource-meta"><span>{resource.type}</span><span>•</span><span>{resource.organization} · {resource.year}</span></div><h3>{resource.title}</h3><p className="resource-description">{resource.description}</p><button className="read-link">Open resource <span>→</span></button></div></article>)}</div>{filtered.length === 0 && <div className="empty-state">No resources match this search.</div>}</PageFrame>
}

export function LandIntelligence() {
  const [layer, setLayer] = useState('Climate vulnerability')
  const layers = ['Climate vulnerability', 'Urban expansion', 'Land cover', 'Infrastructure']
  return <PageFrame page="Land intelligence"><div className="intel-layout"><div className="panel intelligence-map"><div className="panel-heading"><div><p className="eyebrow">LIVE LAYER</p><h2>{layer}</h2></div><select value={layer} onChange={(event) => setLayer(event.target.value)}>{layers.map((item) => <option key={item}>{item}</option>)}</select></div><div className="large-map-stage"><div className="map-grid"></div><div className="india-shape large"></div><span className="map-label intel-label one">HIGH EXPOSURE<br/><b>ODISHA COAST</b></span><span className="map-label intel-label two">URBAN PRESSURE<br/><b>DELHI NCR</b></span><span className="map-label intel-label three">LAND COVER CHANGE<br/><b>WESTERN GHATS</b></span><div className="map-legend"><span><i className="legend-mint"></i>Low</span><span><i className="legend-yellow"></i>Moderate</span><span><i className="legend-coral"></i>High</span></div></div><div className="map-footer"><div><strong>18</strong><span>live data layers</span></div><div><strong>7.4M</strong><span>hectares monitored</span></div><button>Download layer ↧</button></div></div><div className="intel-side"><div className="panel metric-panel"><p className="eyebrow">NATIONAL SIGNAL</p><strong>64.8</strong><span>Climate resilience index</span><div className="metric-bar"><i></i></div><small>+4.2 points since 2024</small></div><div className="panel layer-panel"><p className="eyebrow">AVAILABLE LAYERS</p>{layers.map((item, index) => <button className={layer === item ? 'layer-row active' : 'layer-row'} key={item} onClick={() => setLayer(item)}><span className={`layer-dot dot-${index}`}></span>{item}<b>→</b></button>)}</div></div></div><div className="insight-row"><div><span>✦</span><div><strong>AI-assisted insight</strong><p>Climate exposure is overlapping with rapid urban expansion across 14 districts. Consider prioritizing land readjustment pilots in the next policy cycle.</p></div></div><button>Explore districts →</button></div></PageFrame>
}

export function PolicyLab() {
  const [experiments, setExperiments] = useState(demoExperiments)
  const [status, setStatus] = useState('All experiments')
  useEffect(() => { getExperiments().then(setExperiments) }, [])
  const visible = status === 'All experiments' ? experiments : experiments.filter((item) => item.status === status)
  return <PageFrame page="Policy lab"><div className="lab-toolbar"><div className="tab-list">{['All experiments', 'Pilot', 'Evaluating', 'Scoping'].map((item) => <button className={status === item ? 'active' : ''} onClick={() => setStatus(item)} key={item}>{item}</button>)}</div><button className="green-button">＋ Propose experiment</button></div><div className="experiment-grid">{visible.map((experiment) => <article className="panel experiment-card" key={experiment.id}><div className="experiment-top"><span className={`status-pill ${experiment.status.toLowerCase()}`}>{experiment.status}</span><button className="dots">•••</button></div><p className="eyebrow">{experiment.focus}</p><h2>{experiment.title}</h2><p className="experiment-location">⌖ {experiment.location}</p><div className="experiment-owner"><span className="avatar small">{experiment.owner.slice(0, 2).toUpperCase()}</span><span>Led by <b>{experiment.owner}</b></span></div><div className="experiment-progress"><div><span>Implementation progress</span><b>{experiment.progress}%</b></div><div className="progress"><i style={{ width: `${experiment.progress}%` }}></i></div></div><button className="text-button">View experiment →</button></article>)}</div><div className="simulation-banner"><div><p className="eyebrow">SCENARIO BUILDER</p><h2>Test a reform before it reaches the field.</h2><p>Model likely outcomes across equity, revenue, climate exposure, and implementation complexity.</p></div><button className="green-button">Open simulator →</button></div></PageFrame>
}

export function Collaborate() {
  const [workspaces, setWorkspaces] = useState([{ name: 'Coastal Resilience', description: 'A shared evidence base for resilient land use planning.', members: 8, updated: 'Updated 2 days ago' }, { name: 'Land Dispute Atlas', description: 'Mapping patterns, causes, and resolution pathways.', members: 12, updated: 'Updated 1 week ago' }, { name: 'Urban Transition 2030', description: 'Researching peri-urban land governance and value capture.', members: 5, updated: 'Updated 2 weeks ago' }])
  const [showForm, setShowForm] = useState(false)
  const [name, setName] = useState('')
  const addWorkspace = async (event) => { event.preventDefault(); if (!name.trim()) return; const workspace = { name, description: 'A new shared research workspace.', members: 1, updated: 'Created just now' }; setWorkspaces((current) => [workspace, ...current]); await createWorkspace(name, workspace.description); setName(''); setShowForm(false) }
  return <PageFrame page="Collaborate"><div className="collab-head"><div><h2>Your shared workspaces</h2><p>Collaborate across institutions without losing the thread.</p></div><button className="green-button" onClick={() => setShowForm((value) => !value)}>＋ New workspace</button></div>{showForm && <form className="workspace-form" onSubmit={addWorkspace}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Workspace name" autoFocus /><button className="green-button" type="submit">Create</button></form>}<div className="workspace-grid">{workspaces.map((workspace) => <article className="panel workspace-card" key={workspace.name}><div className="workspace-symbol">◌</div><div className="workspace-card-copy"><h2>{workspace.name}</h2><p>{workspace.description}</p><div><span>◉ {workspace.members} collaborators</span><span>{workspace.updated}</span></div></div><button className="arrow-button">→</button></article>)}</div><div className="collab-banner"><span className="question-mark">?</span><div><strong>Need a research partner?</strong><p>Post a question to the national network and find collaborators with relevant expertise.</p></div><button className="text-button">Ask the network →</button></div></PageFrame>
}

export function InnovationHub() {
  const [calls, setCalls] = useState(demoCalls)
  useEffect(() => { getInnovationCalls().then(setCalls) }, [])
  return <PageFrame page="Innovation hub"><div className="innovation-feature"><div><p className="eyebrow">FEATURED OPPORTUNITY</p><h2>Make land data work for everyone.</h2><p>The 2026 National Land Innovation Challenge is now open to multidisciplinary teams building tools for transparent, resilient, and equitable land governance.</p><button className="green-button">View challenge brief →</button></div><div className="feature-mark">✦<small>2026<br/>OPEN CALL</small></div></div><div className="section-heading hub-heading"><div><p className="eyebrow">OPPORTUNITIES</p><h2>Open calls and programmes</h2></div><button className="text-button">View archive →</button></div><div className="call-grid">{calls.map((call) => <article className="resource-card call-card" key={call.id}><div className={`resource-art ${call.tone || 'mint'}`}><span>{call.type}</span><div className="art-lines"></div></div><div className="resource-body"><h3>{call.title}</h3><div className="call-meta"><span>Deadline <b>{call.deadline}</b></span><span>{call.applicants} applicants</span></div><button className="read-link">See details <span>→</span></button></div></article>)}</div></PageFrame>
}
